update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,17 @@
 #!/usr/bin/env bash
+TENSORFLOW_PATH=${PWD}
+PYTHON_BIN_PATH=$(which python || which python3  || true)
+TF_NEED_GCP=0
+TF_NEED_HDFS=0
+TF_NEED_OPENCL=0
+TF_NEED_CUDA=1
+TF_ENABLE_XLA=0
+GCC_HOST_COMPILER_PATH=$(which gcc || true)
+TF_CUDA_VERSION=8.0
+CUDA_TOOLKIT_PATH=/usr/local/cuda-8.0
+TF_CUDNN_VERSION=5
+CUDNN_INSTALL_PATH=/usr/local/cudnn-v5
+TF_CUDA_COMPUTE_CAPABILITIES=6.1
 
 set -e
 set -o pipefail
@@ -33,6 +46,23 @@ function bazel_clean_and_fetch() {
 }
 
 ## Set up python-related environment settings
+while true; do
+    if [ -z "$TENSORFLOW_PATH"  ]; then
+        default_tensorflow_path=$(pwd)
+        read -p "Please input tensorflow path. [Default is $default_tensorflow_path]: " TENSORFLOW_PATH
+        if [ -z "$TENSORFLOW_PATH"  ]; then
+            TENSORFLOW_PATH=$default_tensorflow_path
+        fi
+    fi
+    if [ -e "$TENSORFLOW_PATH"  ]; then
+        TENSORFLOW_PATH="$TENSORFLOW_PATH/_python_build"
+        export TENSORFLOW_PATH
+        break
+    fi
+    echo "Invalid python path. ${TENSORFLOW_PATH} cannot be found" 1>&2
+    TENSORFLOW_PATH=""
+done
+
 while true; do
   fromuser=""
   if [ -z "$PYTHON_BIN_PATH" ]; then
