can't found cuda and cudnn

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,8 +1,39 @@
 #!/usr/bin/env bash
 
-DO_NOT_SUBMIT_WARNING="Unofficial setting. DO NOT SUBMIT!!!"
+#*******************************************************#
 
+# TENSORFLOW_PATH=${PWD}
+# PYTHON_BIN_PATH=$(which python)
+# TF_NEED_GCP=0
+# TF_NEED_CUDA=1
+# GCC_HOST_COMPILER_PATH=$(which gcc)
+# TF_CUDA_VERSION=7.0
+# CUDA_TOOLKIT_PATH=/usr/local/cuda-7.0
+# TF_CUDNN_VERSION=4
+# CUDNN_INSTALL_PATH=/usr/local/cudnn-v4
+# TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2
+
+#*******************************************************#
+
+DO_NOT_SUBMIT_WARNING="Unofficial setting. DO NOT SUBMIT!!!"
 ## Set up python-related environment settings
+while true; do
+  if [ -z "$TENSORFLOW_PATH" ]; then
+    default_tensorflow_path=$(pwd)
+    read -p "Please input tensorflow path. [Default is $default_tensorflow_path]: " TENSORFLOW_PATH
+    if [ -z "$TENSORFLOW_PATH" ]; then
+      TENSORFLOW_PATH=$default_tensorflow_path
+    fi
+  fi
+  if [ -e "$TENSORFLOW_PATH" ]; then
+    TENSORFLOW_PATH="$TENSORFLOW_PATH/_python_build"
+    export TENSORFLOW_PATH
+    break
+  fi
+  echo "Invalid python path. ${TENSORFLOW_PATH} cannot be found" 1>&2
+  TENSORFLOW_PATH=""
+done
+
 while true; do
   fromuser=""
   if [ -z "$PYTHON_BIN_PATH" ]; then
